openapi: 3.0.3
info:
  version: 0.0.3
  title: OgiriGenerator API
paths:
  /users:
    get:
      operationId: GetUser
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/User"
        default:
          description: デフォルトのエラーレスポンス
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DefaultErrorResponse"
    post:
      operationId: PostUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
      responses:
        "200":
          description: OK
        default:
          description: デフォルトのエラーレスポンス
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DefaultErrorResponse"
  /questions:
    post:
      operationId: PostQuestion
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Question"
      responses:
        "200":
          description: OK
        default:
          description: デフォルトのエラーレスポンス
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DefaultErrorResponse"
  /answers:
    post:
      operationId: PostAnswer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Answer"
      responses:
        "200":
          description: OK
        default:
          description: デフォルトのエラーレスポンス
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DefaultErrorResponse"
  /likes:
    post:
      operationId: PostLike
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Like"
      responses:
        "200":
          description: OK
        default:
          description: デフォルトのエラーレスポンス
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DefaultErrorResponse"
  /questions/byQuestionId:
    get:
      operationId: GetQuestionsByQuestionId
      parameters:
        - name: questionId
          in: query
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Question"
        default:
          description: デフォルトのエラーレスポンス
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DefaultErrorResponse"
  /questions/byUserId:
    get:
      operationId: GetQuestionsByUserId
      parameters:
        - name: userId
          in: query
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Question"
        default:
          description: デフォルトのエラーレスポンス
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DefaultErrorResponse"
  /answers/byUserId:
    get:
      operationId: GetAnswersByUserId
      parameters:
        - name: userId
          in: query
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Answer"
        default:
          description: デフォルトのエラーレスポンス
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DefaultErrorResponse"
  /answers/byQuestionId:
    get:
      operationId: GetAnswersByQuestionId
      parameters:
        - name: questionId
          in: query
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Answer"
        default:
          description: デフォルトのエラーレスポンス
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DefaultErrorResponse"
  /answers/byLike:
    get:
      operationId: GetAnswersByLike
      parameters:
        - name: period
          in: query
          required: true
          schema:
            type: string
        - name: topN
          in: query
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Answer"
        default:
          description: デフォルトのエラーレスポンス
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DefaultErrorResponse"
  /likes/byUserId:
    get:
      operationId: GetLikesByUserId
      parameters:
        - name: userId
          in: query
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Like"
        default:
          description: デフォルトのエラーレスポンス
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DefaultErrorResponse"
components:
  schemas:
    User:
      type: object
      properties:
        userId:
          type: string
        name:
          type: string
      required:
        - userId
        - name
    Answer:
      type: object
      properties:
        answerId:
          type: string
        userId:
          type: string
        questionId:
          type: string
        question:
          type: string
        answer:
          type: string
        isPublic:
          type: boolean
        likes:
          type: integer
        timestamp:
          type: string
          format: date-time
      required:
        - answerId
        - userId
        - questionId
        - question
        - answer
        - isPublic
        - likes
        - timestamp
    Question:
      type: object
      properties:
        questionId:
          type: string
        question:
          type: string
        createdByAI:
          type: boolean
        userId:
          type: string
        timestamp:
          type: string
          format: date-time
      required:
        - questionId
        - question
        - createdByAI
        - userId
        - timestamp
    Like:
      type: object
      properties:
        userId:
          type: string
        answerId:
          type: string
        questionId:
          type: string
        likeId:
          type: string
        timestamp:
          type: string
          format: date-time
      required:
        - userId
        - answerId
        - questionId
        - likeId
        - timestamp
    DefaultErrorResponse:
      type: object
      properties:
        message:
          type: string
